# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16  
    commands:
      - npm install
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm run migrate
  build:
    commands:
      - echo Build started on `date`      
      - npm run test
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  type: zip
  files:
    - '**/*'

cache:
  paths:
    - node_modules

    