# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2
phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      - npm run migrate
  test:
    commands:
      - echo Build started on `date`      
      - npm run test
  post_build:
    commands:
      - echo Build completed on `date`
  cache:
    paths:
      - node_modules

    