apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: "#{APP_NAME}#"
  name: "#{APP_NAME}#"
  namespace: "#{NAMESPACE}#"
spec: 
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0      
  selector: 
    matchLabels: 
      app: "#{APP_NAME}#"
  template:
    metadata:
      labels:
        app: "#{APP_NAME}#"
    spec: 
      containers: 
        - image: "#{GCP_REGISTRY}#/#{GCP_PROJECT_ID}#/#{GCP_REPOSITORY}#/#{APP_NAME}#:#{IMAGE_TAG}#"
          imagePullPolicy: Always
          envFrom:
          - configMapRef:
              name: "#{APP_NAME}#"
          name: "#{APP_NAME}#"
          ports: 
            - containerPort: 80
          resources:
            requests:
              memory: 200Mi
              cpu: 50m
            limits:
              memory: 512Mi
              cpu: 100m
              